import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import create from 'zustand';
import React from 'react';
interface IState {
  name: string[];
  bears: number;
  increasePopulation: () => void;
  decreasePopulation: () => void;
  removeAllBears: () => void;
  setName: (name: string[]) => void;
  removeName: () => void;
}

const useStore = create<IState>((set) => ({
  bears: 0,
  name: [],
  setName: (val: string[]) => set((state) => ({ ...state, name: val })),
  increasePopulation: () => set((state) => ({ bears: state.bears + 1 })),
  decreasePopulation: () => set((state) => ({ bears: state.bears - 1 })),
  removeAllBears: () => set({ bears: 0 }),
  removeName: () => set(() => ({ name: [] })),
}));
const Home: NextPage = () => {
  const inputRef = React.useRef<HTMLInputElement>(null);
  const formRef = React.useRef<HTMLFormElement>(null);
  const {
    bears,
    name,
    increasePopulation,
    removeAllBears,
    decreasePopulation,
    setName,
    removeName,
  } = useStore();
  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    let nameValue: string | undefined = inputRef.current?.value;
    setName([...(name ?? ''), nameValue ?? '']);
    formRef.current?.reset();
  };
  console.log(name);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <p>{bears} tahu</p>
        <button onClick={increasePopulation}>add 1</button>
        <button onClick={decreasePopulation}>decreasePopulation</button>
        <button onClick={removeAllBears}>removeAllBears</button>
      </div>
      <div
        style={{
          paddingTop: '10px',
        }}
      >
        {name.map((n, idx) => {
          return <p key={idx}>{n}</p>;
        })}
        <form onSubmit={handleSubmit} ref={formRef}>
          <input type="text" name="manan" id="1" ref={inputRef} />
          <button type="submit">add string</button>
          <button onClick={removeName}>remove all name</button>
        </form>
      </div>
    </div>
  );
};

export default Home;
